services:
  backend:
    build: ./backend
    image: ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    networks:
      - app-network
