name: Publish Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t <DOCKER_USERNAME>/backend:latest ./backend
          docker push <DOCKER_USERNAME>/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t <DOCKER_USERNAME>/frontend:latest ./frontend
          docker push <DOCKER_USERNAME>/frontend:latest
