name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/frontend-app
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/backend-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build frontend Docker image
        run: docker build -t ${{ env.FRONTEND_IMAGE_NAME }}:latest ./frontend

      - name: Build backend Docker image
        run: docker build -t ${{ env.BACKEND_IMAGE_NAME }}:latest ./backend

      - name: Verify built images
        run: docker images

  push_to_registry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push frontend Docker image
        run: |
          docker tag ${{ env.FRONTEND_IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Tag and Push backend Docker image
        run: |
          docker tag ${{ env.BACKEND_IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
